
package mn.gov.xyp.insurance;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsuranceService", targetNamespace = "http://insurance.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsuranceService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100504_confirmAppUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100504_confirmAppUser", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100504ConfirmAppUser")
    @ResponseWrapper(localName = "WS100504_confirmAppUserResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100504ConfirmAppUserResponse")
    public ServiceResponse ws100504ConfirmAppUser(
        @WebParam(name = "request", targetNamespace = "")
        ServiceConfirmAppUserRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100522_checkHouseHoldSC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100522_checkHouseHoldSC", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100522CheckHouseHoldSC")
    @ResponseWrapper(localName = "WS100522_checkHouseHoldSCResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100522CheckHouseHoldSCResponse")
    public ServiceResponse ws100522CheckHouseHoldSC(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100592_GetInvoiceByNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100592_GetInvoiceByNumber", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100592GetInvoiceByNumber")
    @ResponseWrapper(localName = "WS100592_GetInvoiceByNumberResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100592GetInvoiceByNumberResponse")
    public ServiceResponse ws100592GetInvoiceByNumber(
        @WebParam(name = "request", targetNamespace = "")
        GetInvoiceByNumberRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100596_GetInsuranceL")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100596_GetInsuranceL", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100596GetInsuranceL")
    @ResponseWrapper(localName = "WS100596_GetInsuranceLResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100596GetInsuranceLResponse")
    public ServiceResponse ws100596GetInsuranceL(
        @WebParam(name = "request", targetNamespace = "")
        GetInsuranceLRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100550_pregnancyChildbirthCertList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100550_pregnancyChildbirthCertList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100550PregnancyChildbirthCertList")
    @ResponseWrapper(localName = "WS100550_pregnancyChildbirthCertListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100550PregnancyChildbirthCertListResponse")
    public ServiceResponse ws100550PregnancyChildbirthCertList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100516_getInsuredForLastThreeMonthInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100516_getInsuredForLastThreeMonthInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100516GetInsuredForLastThreeMonthInfo")
    @ResponseWrapper(localName = "WS100516_getInsuredForLastThreeMonthInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100516GetInsuredForLastThreeMonthInfoResponse")
    public ServiceResponse ws100516GetInsuredForLastThreeMonthInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100535_findOrganizationForMedicalCert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100535_findOrganizationForMedicalCert", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100535FindOrganizationForMedicalCert")
    @ResponseWrapper(localName = "WS100535_findOrganizationForMedicalCertResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100535FindOrganizationForMedicalCertResponse")
    public ServiceResponse ws100535FindOrganizationForMedicalCert(
        @WebParam(name = "request", targetNamespace = "")
        FindOrganizationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100555_getBankList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100555_getBankList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100555GetBankList")
    @ResponseWrapper(localName = "WS100555_getBankListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100555GetBankListResponse")
    public ServiceResponse ws100555GetBankList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100590_CitizenAccountInformationRetrievalService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100590_CitizenAccountInformationRetrievalService", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100590CitizenAccountInformationRetrievalService")
    @ResponseWrapper(localName = "WS100590_CitizenAccountInformationRetrievalServiceResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100590CitizenAccountInformationRetrievalServiceResponse")
    public ServiceResponse ws100590CitizenAccountInformationRetrievalService(
        @WebParam(name = "request", targetNamespace = "")
        CitizenAccountInformationRetrievalServiceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100551_pregnancyBenefitsApply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100551_pregnancyBenefitsApply", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100551PregnancyBenefitsApply")
    @ResponseWrapper(localName = "WS100551_pregnancyBenefitsApplyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100551PregnancyBenefitsApplyResponse")
    public ServiceResponse ws100551PregnancyBenefitsApply(
        @WebParam(name = "request", targetNamespace = "")
        PregnancyBenefitsApplyRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100505_createAppUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100505_createAppUser", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100505CreateAppUser")
    @ResponseWrapper(localName = "WS100505_createAppUserResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100505CreateAppUserResponse")
    public ServiceResponse ws100505CreateAppUser(
        @WebParam(name = "request", targetNamespace = "")
        ServiceCreateAppUserRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100552_unemploymentBenefitsList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100552_unemploymentBenefitsList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100552UnemploymentBenefitsList")
    @ResponseWrapper(localName = "WS100552_unemploymentBenefitsListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100552UnemploymentBenefitsListResponse")
    public ServiceResponse ws100552UnemploymentBenefitsList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100506_findAppUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100506_findAppUser", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100506FindAppUser")
    @ResponseWrapper(localName = "WS100506_findAppUserResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100506FindAppUserResponse")
    public ServiceResponse ws100506FindAppUser(
        @WebParam(name = "request", targetNamespace = "")
        ServiceFindAppUserRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100510_getSiWorkerAccountInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100510_getSiWorkerAccountInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100510GetSiWorkerAccountInfo")
    @ResponseWrapper(localName = "WS100510_getSiWorkerAccountInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100510GetSiWorkerAccountInfoResponse")
    public ServiceResponse ws100510GetSiWorkerAccountInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100523_getCampVoucherOfElderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100523_getCampVoucherOfElderInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100523GetCampVoucherOfElderInfo")
    @ResponseWrapper(localName = "WS100523_getCampVoucherOfElderInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100523GetCampVoucherOfElderInfoResponse")
    public ServiceResponse ws100523GetCampVoucherOfElderInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100595_SetInvoicePayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100595_SetInvoicePayment", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100595SetInvoicePayment")
    @ResponseWrapper(localName = "WS100595_SetInvoicePaymentResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100595SetInvoicePaymentResponse")
    public ServiceResponse ws100595SetInvoicePayment(
        @WebParam(name = "request", targetNamespace = "")
        SetInvoicePaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100567_lostCaregiverPensionDocumentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100567_lostCaregiverPensionDocumentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100567LostCaregiverPensionDocumentInfo")
    @ResponseWrapper(localName = "WS100567_lostCaregiverPensionDocumentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100567LostCaregiverPensionDocumentInfoResponse")
    public ServiceResponse ws100567LostCaregiverPensionDocumentInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100549_disabilityBenefitsApply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100549_disabilityBenefitsApply", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100549DisabilityBenefitsApply")
    @ResponseWrapper(localName = "WS100549_disabilityBenefitsApplyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100549DisabilityBenefitsApplyResponse")
    public ServiceResponse ws100549DisabilityBenefitsApply(
        @WebParam(name = "request", targetNamespace = "")
        DisabilityBenefitsApplyRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100589_ListOfInvestmentRequests")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100589_ListOfInvestmentRequests", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100589ListOfInvestmentRequests")
    @ResponseWrapper(localName = "WS100589_ListOfInvestmentRequestsResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100589ListOfInvestmentRequestsResponse")
    public ServiceResponse ws100589ListOfInvestmentRequests(
        @WebParam(name = "request", targetNamespace = "")
        ListOfInvestmentRequestsRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100509_getSalaryFoundByIndutyInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100509_getSalaryFoundByIndutyInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100509GetSalaryFoundByIndutyInfo")
    @ResponseWrapper(localName = "WS100509_getSalaryFoundByIndutyInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100509GetSalaryFoundByIndutyInfoResponse")
    public ServiceResponse ws100509GetSalaryFoundByIndutyInfo(
        @WebParam(name = "request", targetNamespace = "")
        SalaryFoundByOccupationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100527_getPaymentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100527_getPaymentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100527GetPaymentInfo")
    @ResponseWrapper(localName = "WS100527_getPaymentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100527GetPaymentInfoResponse")
    public ServiceResponse ws100527GetPaymentInfo(
        @WebParam(name = "request", targetNamespace = "")
        PaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100545_medicalCertCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100545_medicalCertCheck", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100545MedicalCertCheck")
    @ResponseWrapper(localName = "WS100545_medicalCertCheckResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100545MedicalCertCheckResponse")
    public ServiceResponse ws100545MedicalCertCheck(
        @WebParam(name = "request", targetNamespace = "")
        MedicalCertCheckRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100578_disabledHumanEnglishInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100578_disabledHumanEnglishInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100578DisabledHumanEnglishInfo")
    @ResponseWrapper(localName = "WS100578_disabledHumanEnglishInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100578DisabledHumanEnglishInfoResponse")
    public ServiceResponse ws100578DisabledHumanEnglishInfo(
        @WebParam(name = "request", targetNamespace = "")
        DisabledHumanInfoEnglishRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100521_checkHouseHoldFood")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100521_checkHouseHoldFood", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100521CheckHouseHoldFood")
    @ResponseWrapper(localName = "WS100521_checkHouseHoldFoodResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100521CheckHouseHoldFoodResponse")
    public ServiceResponse ws100521CheckHouseHoldFood(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100594_GetInsuranceProducts")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100594_GetInsuranceProducts", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100594GetInsuranceProducts")
    @ResponseWrapper(localName = "WS100594_GetInsuranceProductsResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100594GetInsuranceProductsResponse")
    public ServiceResponse ws100594GetInsuranceProducts();

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100520_checkHouseHoldChild")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100520_checkHouseHoldChild", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100520CheckHouseHoldChild")
    @ResponseWrapper(localName = "WS100520_checkHouseHoldChildResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100520CheckHouseHoldChildResponse")
    public ServiceResponse ws100520CheckHouseHoldChild(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100566_disabilityPensionDocumentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100566_disabilityPensionDocumentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100566DisabilityPensionDocumentInfo")
    @ResponseWrapper(localName = "WS100566_disabilityPensionDocumentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100566DisabilityPensionDocumentInfoResponse")
    public ServiceResponse ws100566DisabilityPensionDocumentInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100503_getCheckMotherTimeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100503_getCheckMotherTimeInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100503GetCheckMotherTimeInfo")
    @ResponseWrapper(localName = "WS100503_getCheckMotherTimeInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100503GetCheckMotherTimeInfoResponse")
    public ServiceResponse ws100503GetCheckMotherTimeInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100533_insuredListLast3MonthByDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100533_insuredListLast3MonthByDate", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100533InsuredListLast3MonthByDate")
    @ResponseWrapper(localName = "WS100533_insuredListLast3MonthByDateResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100533InsuredListLast3MonthByDateResponse")
    public ServiceResponse ws100533InsuredListLast3MonthByDate(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100525_getOrganizationDeptInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100525_getOrganizationDeptInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100525GetOrganizationDeptInfo")
    @ResponseWrapper(localName = "WS100525_getOrganizationDeptInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100525GetOrganizationDeptInfoResponse")
    public ServiceResponse ws100525GetOrganizationDeptInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceOrganizationDeptRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100546_disabilityMedicalCertEdit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100546_disabilityMedicalCertEdit", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100546DisabilityMedicalCertEdit")
    @ResponseWrapper(localName = "WS100546_disabilityMedicalCertEditResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100546DisabilityMedicalCertEditResponse")
    public ServiceResponse ws100546DisabilityMedicalCertEdit(
        @WebParam(name = "request", targetNamespace = "")
        DisabilityMedicalCertEditRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100554_unemploymentBenefitsCount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100554_unemploymentBenefitsCount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100554UnemploymentBenefitsCount")
    @ResponseWrapper(localName = "WS100554_unemploymentBenefitsCountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100554UnemploymentBenefitsCountResponse")
    public ServiceResponse ws100554UnemploymentBenefitsCount(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100560_refundHalfAccountList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100560_refundHalfAccountList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100560RefundHalfAccountList")
    @ResponseWrapper(localName = "WS100560_refundHalfAccountListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100560RefundHalfAccountListResponse")
    public ServiceResponse ws100560RefundHalfAccountList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100534_organizationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100534_organizationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100534OrganizationInfo")
    @ResponseWrapper(localName = "WS100534_organizationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100534OrganizationInfoResponse")
    public ServiceResponse ws100534OrganizationInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceOrganizationDeptRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100538_disabilityMedicalCertInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100538_disabilityMedicalCertInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100538DisabilityMedicalCertInfo")
    @ResponseWrapper(localName = "WS100538_disabilityMedicalCertInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100538DisabilityMedicalCertInfoResponse")
    public ServiceResponse ws100538DisabilityMedicalCertInfo(
        @WebParam(name = "request", targetNamespace = "")
        DisabilityMedicalCertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100559_refundHalfBankList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100559_refundHalfBankList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100559RefundHalfBankList")
    @ResponseWrapper(localName = "WS100559_refundHalfBankListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100559RefundHalfBankListResponse")
    public ServiceResponse ws100559RefundHalfBankList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100543_retirementListInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100543_retirementListInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100543RetirementListInfo")
    @ResponseWrapper(localName = "WS100543_retirementListInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100543RetirementListInfoResponse")
    public ServiceResponse ws100543RetirementListInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckPensionDateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100524_getDisabledPersonSupplyInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100524_getDisabledPersonSupplyInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100524GetDisabledPersonSupplyInfo")
    @ResponseWrapper(localName = "WS100524_getDisabledPersonSupplyInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100524GetDisabledPersonSupplyInfoResponse")
    public ServiceResponse ws100524GetDisabledPersonSupplyInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100586_OrgHasDebt")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100586_OrgHasDebt", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100586OrgHasDebt")
    @ResponseWrapper(localName = "WS100586_OrgHasDebtResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100586OrgHasDebtResponse")
    public ServiceResponse ws100586OrgHasDebt(
        @WebParam(name = "request", targetNamespace = "")
        OrgHasDebtRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100511_getEmployerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100511_getEmployerInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100511GetEmployerInfo")
    @ResponseWrapper(localName = "WS100511_getEmployerInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100511GetEmployerInfoResponse")
    public ServiceResponse ws100511GetEmployerInfo(
        @WebParam(name = "request", targetNamespace = "")
        EmployerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100579_pensionFiveYearsAverageChange")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100579_pensionFiveYearsAverageChange", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100579PensionFiveYearsAverageChange")
    @ResponseWrapper(localName = "WS100579_pensionFiveYearsAverageChangeResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100579PensionFiveYearsAverageChangeResponse")
    public ServiceResponse ws100579PensionFiveYearsAverageChange(
        @WebParam(name = "request", targetNamespace = "")
        PensionFiveYearsAverageChangeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100529_getSalaryFeeList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100529_getSalaryFeeList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100529GetSalaryFeeList")
    @ResponseWrapper(localName = "WS100529_getSalaryFeeListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100529GetSalaryFeeListResponse")
    public ServiceResponse ws100529GetSalaryFeeList(
        @WebParam(name = "request", targetNamespace = "")
        GetSalaryFeeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100562_refundHalfUpdateAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100562_refundHalfUpdateAccount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100562RefundHalfUpdateAccount")
    @ResponseWrapper(localName = "WS100562_refundHalfUpdateAccountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100562RefundHalfUpdateAccountResponse")
    public ServiceResponse ws100562RefundHalfUpdateAccount(
        @WebParam(name = "request", targetNamespace = "")
        RefundHalfAccountRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100575_farmersVoluntaryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100575_farmersVoluntaryInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100575FarmersVoluntaryInfo")
    @ResponseWrapper(localName = "WS100575_farmersVoluntaryInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100575FarmersVoluntaryInfoResponse")
    public ServiceResponse ws100575FarmersVoluntaryInfo(
        @WebParam(name = "request", targetNamespace = "")
        FarmersVoluntaryInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100528_paymentLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100528_paymentLog", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100528PaymentLog")
    @ResponseWrapper(localName = "WS100528_paymentLogResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100528PaymentLogResponse")
    public ServiceResponse ws100528PaymentLog(
        @WebParam(name = "request", targetNamespace = "")
        PaymentLogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100536_checkMotherEmployed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100536_checkMotherEmployed", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100536CheckMotherEmployed")
    @ResponseWrapper(localName = "WS100536_checkMotherEmployedResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100536CheckMotherEmployedResponse")
    public ServiceResponse ws100536CheckMotherEmployed(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100582_enterprisesOrgContributionInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100582_enterprisesOrgContributionInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100582EnterprisesOrgContributionInfo")
    @ResponseWrapper(localName = "WS100582_enterprisesOrgContributionInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100582EnterprisesOrgContributionInfoResponse")
    public ServiceResponse ws100582EnterprisesOrgContributionInfo(
        @WebParam(name = "request", targetNamespace = "")
        EnterprisesOrgContributionInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100553_unemploymentBenefitsApply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100553_unemploymentBenefitsApply", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100553UnemploymentBenefitsApply")
    @ResponseWrapper(localName = "WS100553_unemploymentBenefitsApplyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100553UnemploymentBenefitsApplyResponse")
    public ServiceResponse ws100553UnemploymentBenefitsApply(
        @WebParam(name = "request", targetNamespace = "")
        UnemploymentBenefitsApplyRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100558_orgInfoForStatistic")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100558_orgInfoForStatistic", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100558OrgInfoForStatistic")
    @ResponseWrapper(localName = "WS100558_orgInfoForStatisticResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100558OrgInfoForStatisticResponse")
    public ServiceResponse ws100558OrgInfoForStatistic(
        @WebParam(name = "request", targetNamespace = "")
        OrgInfoForStatisticRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100565_getCitizenSalaryInfoEng")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100565_getCitizenSalaryInfoEng", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100565GetCitizenSalaryInfoEng")
    @ResponseWrapper(localName = "WS100565_getCitizenSalaryInfoEngResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100565GetCitizenSalaryInfoEngResponse")
    public ServiceResponse ws100565GetCitizenSalaryInfoEng(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceCitizenEngRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100580_pensionFiveYearsAverageCheckStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100580_pensionFiveYearsAverageCheckStatus", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100580PensionFiveYearsAverageCheckStatus")
    @ResponseWrapper(localName = "WS100580_pensionFiveYearsAverageCheckStatusResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100580PensionFiveYearsAverageCheckStatusResponse")
    public ServiceResponse ws100580PensionFiveYearsAverageCheckStatus(
        @WebParam(name = "request", targetNamespace = "")
        PensionFiveYearsAverageCheckStatusRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100569_disabilityPensionDocumentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100569_disabilityPensionDocumentEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100569DisabilityPensionDocumentEngInfo")
    @ResponseWrapper(localName = "WS100569_disabilityPensionDocumentEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100569DisabilityPensionDocumentEngInfoResponse")
    public ServiceResponse ws100569DisabilityPensionDocumentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredEngRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100542_socialInsuranceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100542_socialInsuranceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100542SocialInsuranceInfo")
    @ResponseWrapper(localName = "WS100542_socialInsuranceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100542SocialInsuranceInfoResponse")
    public ServiceResponse ws100542SocialInsuranceInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100537_pregnancyChildbirthInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100537_pregnancyChildbirthInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100537PregnancyChildbirthInfo")
    @ResponseWrapper(localName = "WS100537_pregnancyChildbirthInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100537PregnancyChildbirthInfoResponse")
    public ServiceResponse ws100537PregnancyChildbirthInfo(
        @WebParam(name = "request", targetNamespace = "")
        PregnancyChildbirthInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100576_insuranceInfoByOrgService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100576_insuranceInfoByOrgService", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100576InsuranceInfoByOrgService")
    @ResponseWrapper(localName = "WS100576_insuranceInfoByOrgServiceResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100576InsuranceInfoByOrgServiceResponse")
    public ServiceResponse ws100576InsuranceInfoByOrgService(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceInfoByOrgRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100597_InvestmentFinancialInstrument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100597_InvestmentFinancialInstrument", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100597InvestmentFinancialInstrument")
    @ResponseWrapper(localName = "WS100597_InvestmentFinancialInstrumentResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100597InvestmentFinancialInstrumentResponse")
    public ServiceResponse ws100597InvestmentFinancialInstrument(
        @WebParam(name = "request", targetNamespace = "")
        InvestmentFinancialInstrumentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100584_GetTotalWorkMonth")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100584_GetTotalWorkMonth", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100584GetTotalWorkMonth")
    @ResponseWrapper(localName = "WS100584_GetTotalWorkMonthResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100584GetTotalWorkMonthResponse")
    public ServiceResponse ws100584GetTotalWorkMonth(
        @WebParam(name = "request", targetNamespace = "")
        GetTotalWorkMonthRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100507_getInsureeWorkHistoryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100507_getInsureeWorkHistoryInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100507GetInsureeWorkHistoryInfo")
    @ResponseWrapper(localName = "WS100507_getInsureeWorkHistoryInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100507GetInsureeWorkHistoryInfoResponse")
    public ServiceResponse ws100507GetInsureeWorkHistoryInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100501_getCitizenSalaryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100501_getCitizenSalaryInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100501GetCitizenSalaryInfo")
    @ResponseWrapper(localName = "WS100501_getCitizenSalaryInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100501GetCitizenSalaryInfoResponse")
    public ServiceResponse ws100501GetCitizenSalaryInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceCitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100588_SendInvestmentRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100588_SendInvestmentRequest", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100588SendInvestmentRequest")
    @ResponseWrapper(localName = "WS100588_SendInvestmentRequestResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100588SendInvestmentRequestResponse")
    public ServiceResponse ws100588SendInvestmentRequest(
        @WebParam(name = "request", targetNamespace = "")
        SendInvestmentRequestRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100585_GetOrgBenNumBy36Month")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100585_GetOrgBenNumBy36Month", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100585GetOrgBenNumBy36Month")
    @ResponseWrapper(localName = "WS100585_GetOrgBenNumBy36MonthResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100585GetOrgBenNumBy36MonthResponse")
    public ServiceResponse ws100585GetOrgBenNumBy36Month(
        @WebParam(name = "request", targetNamespace = "")
        GetOrgBenNumBy36MonthRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100556_getHealthInsuranceFee")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100556_getHealthInsuranceFee", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100556GetHealthInsuranceFee")
    @ResponseWrapper(localName = "WS100556_getHealthInsuranceFeeResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100556GetHealthInsuranceFeeResponse")
    public ServiceResponse ws100556GetHealthInsuranceFee(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100573_orgDebtWithTransacInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100573_orgDebtWithTransacInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100573OrgDebtWithTransacInfo")
    @ResponseWrapper(localName = "WS100573_orgDebtWithTransacInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100573OrgDebtWithTransacInfoResponse")
    public ServiceResponse ws100573OrgDebtWithTransacInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceOrganizationDeptRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100518_getPensionInformationData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100518_getPensionInformationData", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100518GetPensionInformationData")
    @ResponseWrapper(localName = "WS100518_getPensionInformationDataResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100518GetPensionInformationDataResponse")
    public ServiceResponse ws100518GetPensionInformationData(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100502_getCitizenPensionInquiry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100502_getCitizenPensionInquiry", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100502GetCitizenPensionInquiry")
    @ResponseWrapper(localName = "WS100502_getCitizenPensionInquiryResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100502GetCitizenPensionInquiryResponse")
    public ServiceResponse ws100502GetCitizenPensionInquiry(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceCitizenRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100531_checkPensionDate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100531_checkPensionDate", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100531CheckPensionDate")
    @ResponseWrapper(localName = "WS100531_checkPensionDateResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100531CheckPensionDateResponse")
    public ServiceResponse ws100531CheckPensionDate(
        @WebParam(name = "request", targetNamespace = "")
        CheckPensionDateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100598_InvestmentCommercialBanks")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100598_InvestmentCommercialBanks", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100598InvestmentCommercialBanks")
    @ResponseWrapper(localName = "WS100598_InvestmentCommercialBanksResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100598InvestmentCommercialBanksResponse")
    public ServiceResponse ws100598InvestmentCommercialBanks(
        @WebParam(name = "request", targetNamespace = "")
        InvestmentCommercialBanksRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100512_checkIsInsuredInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100512_checkIsInsuredInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100512CheckIsInsuredInfo")
    @ResponseWrapper(localName = "WS100512_checkIsInsuredInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100512CheckIsInsuredInfoResponse")
    public ServiceResponse ws100512CheckIsInsuredInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100532_citizenLossOfAbilityToWorkInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100532_citizenLossOfAbilityToWorkInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100532CitizenLossOfAbilityToWorkInfo")
    @ResponseWrapper(localName = "WS100532_citizenLossOfAbilityToWorkInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100532CitizenLossOfAbilityToWorkInfoResponse")
    public ServiceResponse ws100532CitizenLossOfAbilityToWorkInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckPensionDateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100564_pensionDocumentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100564_pensionDocumentInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100564PensionDocumentInfo")
    @ResponseWrapper(localName = "WS100564_pensionDocumentInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100564PensionDocumentInfoResponse")
    public ServiceResponse ws100564PensionDocumentInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100526_reportLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100526_reportLog", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100526ReportLog")
    @ResponseWrapper(localName = "WS100526_reportLogResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100526ReportLogResponse")
    public ServiceResponse ws100526ReportLog(
        @WebParam(name = "request", targetNamespace = "")
        ReportLogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100563_funeralAllowanceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100563_funeralAllowanceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100563FuneralAllowanceInfo")
    @ResponseWrapper(localName = "WS100563_funeralAllowanceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100563FuneralAllowanceInfoResponse")
    public ServiceResponse ws100563FuneralAllowanceInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100539_pregnancyChildbirthCertInvalid")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100539_pregnancyChildbirthCertInvalid", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100539PregnancyChildbirthCertInvalid")
    @ResponseWrapper(localName = "WS100539_pregnancyChildbirthCertInvalidResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100539PregnancyChildbirthCertInvalidResponse")
    public ServiceResponse ws100539PregnancyChildbirthCertInvalid(
        @WebParam(name = "request", targetNamespace = "")
        MedicalCertInvalidRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100513_findOrganizationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100513_findOrganizationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100513FindOrganizationInfo")
    @ResponseWrapper(localName = "WS100513_findOrganizationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100513FindOrganizationInfoResponse")
    public ServiceResponse ws100513FindOrganizationInfo(
        @WebParam(name = "request", targetNamespace = "")
        FindOrganizationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100572_GetPensionInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100572_GetPensionInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100572GetPensionInfo")
    @ResponseWrapper(localName = "WS100572_GetPensionInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100572GetPensionInfoResponse")
    public ServiceResponse ws100572GetPensionInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100517_checkMotherTimeAllInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100517_checkMotherTimeAllInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100517CheckMotherTimeAllInfo")
    @ResponseWrapper(localName = "WS100517_checkMotherTimeAllInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100517CheckMotherTimeAllInfoResponse")
    public ServiceResponse ws100517CheckMotherTimeAllInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeAllRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100583_GetMonetizedIncomeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100583_GetMonetizedIncomeInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100583GetMonetizedIncomeInfo")
    @ResponseWrapper(localName = "WS100583_GetMonetizedIncomeInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100583GetMonetizedIncomeInfoResponse")
    public ServiceResponse ws100583GetMonetizedIncomeInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetMonetizedIncomeInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100514_getEmployerNumWithDeptInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100514_getEmployerNumWithDeptInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100514GetEmployerNumWithDeptInfo")
    @ResponseWrapper(localName = "WS100514_getEmployerNumWithDeptInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100514GetEmployerNumWithDeptInfoResponse")
    public ServiceResponse ws100514GetEmployerNumWithDeptInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetEmployerNumWithDeptRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100540_disabilityMedicalCertInvalid")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100540_disabilityMedicalCertInvalid", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100540DisabilityMedicalCertInvalid")
    @ResponseWrapper(localName = "WS100540_disabilityMedicalCertInvalidResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100540DisabilityMedicalCertInvalidResponse")
    public ServiceResponse ws100540DisabilityMedicalCertInvalid(
        @WebParam(name = "request", targetNamespace = "")
        MedicalCertInvalidRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100593_GetBankAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100593_GetBankAccount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100593GetBankAccount")
    @ResponseWrapper(localName = "WS100593_GetBankAccountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100593GetBankAccountResponse")
    public ServiceResponse ws100593GetBankAccount(
        @WebParam(name = "request", targetNamespace = "")
        GetBankAccountsRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100557_citizenInsuranceInfoForStatistic")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100557_citizenInsuranceInfoForStatistic", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100557CitizenInsuranceInfoForStatistic")
    @ResponseWrapper(localName = "WS100557_citizenInsuranceInfoForStatisticResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100557CitizenInsuranceInfoForStatisticResponse")
    public ServiceResponse ws100557CitizenInsuranceInfoForStatistic(
        @WebParam(name = "request", targetNamespace = "")
        CitizenInsuranceInfoForStatRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100515_foreignEmployerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100515_foreignEmployerInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100515ForeignEmployerInfo")
    @ResponseWrapper(localName = "WS100515_foreignEmployerInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100515ForeignEmployerInfoResponse")
    public ServiceResponse ws100515ForeignEmployerInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetEmployerNumWithDeptRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100508_getSalaryFoundByOccupationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100508_getSalaryFoundByOccupationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100508GetSalaryFoundByOccupationInfo")
    @ResponseWrapper(localName = "WS100508_getSalaryFoundByOccupationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100508GetSalaryFoundByOccupationInfoResponse")
    public ServiceResponse ws100508GetSalaryFoundByOccupationInfo(
        @WebParam(name = "request", targetNamespace = "")
        SalaryFoundByOccupationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100561_refundHalfCreateAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100561_refundHalfCreateAccount", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100561RefundHalfCreateAccount")
    @ResponseWrapper(localName = "WS100561_refundHalfCreateAccountResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100561RefundHalfCreateAccountResponse")
    public ServiceResponse ws100561RefundHalfCreateAccount(
        @WebParam(name = "request", targetNamespace = "")
        RefundHalfAccountRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100581_insuranceOrgContributionInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100581_insuranceOrgContributionInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100581InsuranceOrgContributionInfo")
    @ResponseWrapper(localName = "WS100581_insuranceOrgContributionInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100581InsuranceOrgContributionInfoResponse")
    public ServiceResponse ws100581InsuranceOrgContributionInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceOrgContributionInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100574_disabledHumanInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100574_disabledHumanInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100574DisabledHumanInfo")
    @ResponseWrapper(localName = "WS100574_disabledHumanInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100574DisabledHumanInfoResponse")
    public ServiceResponse ws100574DisabledHumanInfo(
        @WebParam(name = "request", targetNamespace = "")
        DisabledHumanInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100530_organizationEmployeeInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100530_organizationEmployeeInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100530OrganizationEmployeeInfo")
    @ResponseWrapper(localName = "WS100530_organizationEmployeeInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100530OrganizationEmployeeInfoResponse")
    public ServiceResponse ws100530OrganizationEmployeeInfo(
        @WebParam(name = "request", targetNamespace = "")
        OrganizationEmployeeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100544_getInsuredForLastThreeMonthOccupationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100544_getInsuredForLastThreeMonthOccupationInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100544GetInsuredForLastThreeMonthOccupationInfo")
    @ResponseWrapper(localName = "WS100544_getInsuredForLastThreeMonthOccupationInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100544GetInsuredForLastThreeMonthOccupationInfoResponse")
    public ServiceResponse ws100544GetInsuredForLastThreeMonthOccupationInfo(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100547_pregnancyChildbirthEdit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100547_pregnancyChildbirthEdit", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100547PregnancyChildbirthEdit")
    @ResponseWrapper(localName = "WS100547_pregnancyChildbirthEditResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100547PregnancyChildbirthEditResponse")
    public ServiceResponse ws100547PregnancyChildbirthEdit(
        @WebParam(name = "request", targetNamespace = "")
        PregnancyChildbirthEditRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100591_InformationOnTheBudgetService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100591_InformationOnTheBudgetService", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100591InformationOnTheBudgetService")
    @ResponseWrapper(localName = "WS100591_InformationOnTheBudgetServiceResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100591InformationOnTheBudgetServiceResponse")
    public ServiceResponse ws100591InformationOnTheBudgetService(
        @WebParam(name = "request", targetNamespace = "")
        InformationOnTheBudgetServiceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100587_CheckInsuredEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100587_CheckInsuredEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100587CheckInsuredEngInfo")
    @ResponseWrapper(localName = "WS100587_CheckInsuredEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100587CheckInsuredEngInfoResponse")
    public ServiceResponse ws100587CheckInsuredEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckInsuredEngInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100571_UMNSInsuranceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100571_UMNSInsuranceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100571UMNSInsuranceInfo")
    @ResponseWrapper(localName = "WS100571_UMNSInsuranceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100571UMNSInsuranceInfoResponse")
    public ServiceResponse ws100571UMNSInsuranceInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100541_healthInsuranceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100541_healthInsuranceInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100541HealthInsuranceInfo")
    @ResponseWrapper(localName = "WS100541_healthInsuranceInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100541HealthInsuranceInfoResponse")
    public ServiceResponse ws100541HealthInsuranceInfo(
        @WebParam(name = "request", targetNamespace = "")
        InsuranceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100519_checkChildMoney")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100519_checkChildMoney", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100519CheckChildMoney")
    @ResponseWrapper(localName = "WS100519_checkChildMoneyResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100519CheckChildMoneyResponse")
    public ServiceResponse ws100519CheckChildMoney(
        @WebParam(name = "request", targetNamespace = "")
        CheckMotherTimeRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100577_getSiSalaryInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100577_getSiSalaryInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100577GetSiSalaryInfo")
    @ResponseWrapper(localName = "WS100577_getSiSalaryInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100577GetSiSalaryInfoResponse")
    public ServiceResponse ws100577GetSiSalaryInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetSiSalaryInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100568_pensionDocumentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100568_pensionDocumentEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100568PensionDocumentEngInfo")
    @ResponseWrapper(localName = "WS100568_pensionDocumentEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100568PensionDocumentEngInfoResponse")
    public ServiceResponse ws100568PensionDocumentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredEngRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100548_disabilityMedicalCertList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100548_disabilityMedicalCertList", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100548DisabilityMedicalCertList")
    @ResponseWrapper(localName = "WS100548_disabilityMedicalCertListResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100548DisabilityMedicalCertListResponse")
    public ServiceResponse ws100548DisabilityMedicalCertList(
        @WebParam(name = "request", targetNamespace = "")
        WorkHistoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.insurance.ServiceResponse
     */
    @WebMethod(operationName = "WS100570_lostCaregiverPensionDocumentEngInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100570_lostCaregiverPensionDocumentEngInfo", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100570LostCaregiverPensionDocumentEngInfo")
    @ResponseWrapper(localName = "WS100570_lostCaregiverPensionDocumentEngInfoResponse", targetNamespace = "http://insurance.xyp.gov.mn/", className = "mn.gov.xyp.insurance.WS100570LostCaregiverPensionDocumentEngInfoResponse")
    public ServiceResponse ws100570LostCaregiverPensionDocumentEngInfo(
        @WebParam(name = "request", targetNamespace = "")
        CheckIsInsuredEngRequestData request);

}
