
package mn.gov.xyp.insurance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsuranceServiceService", targetNamespace = "http://insurance.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/insurance-1.5.0/ws?WSDL")
public class InsuranceServiceService
    extends Service
{

    private final static URL INSURANCESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException INSURANCESERVICESERVICE_EXCEPTION;
    private final static QName INSURANCESERVICESERVICE_QNAME = new QName("http://insurance.xyp.gov.mn/", "InsuranceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/insurance-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSURANCESERVICESERVICE_WSDL_LOCATION = url;
        INSURANCESERVICESERVICE_EXCEPTION = e;
    }

    public InsuranceServiceService() {
        super(__getWsdlLocation(), INSURANCESERVICESERVICE_QNAME);
    }

    public InsuranceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSURANCESERVICESERVICE_QNAME, features);
    }

    public InsuranceServiceService(URL wsdlLocation) {
        super(wsdlLocation, INSURANCESERVICESERVICE_QNAME);
    }

    public InsuranceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSURANCESERVICESERVICE_QNAME, features);
    }

    public InsuranceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsuranceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsuranceService
     */
    @WebEndpoint(name = "InsuranceServicePort")
    public InsuranceService getInsuranceServicePort() {
        return super.getPort(new QName("http://insurance.xyp.gov.mn/", "InsuranceServicePort"), InsuranceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsuranceService
     */
    @WebEndpoint(name = "InsuranceServicePort")
    public InsuranceService getInsuranceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://insurance.xyp.gov.mn/", "InsuranceServicePort"), InsuranceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSURANCESERVICESERVICE_EXCEPTION!= null) {
            throw INSURANCESERVICESERVICE_EXCEPTION;
        }
        return INSURANCESERVICESERVICE_WSDL_LOCATION;
    }

}
