
package mn.gov.xyp.transport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransportService", targetNamespace = "http://transport.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransportService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100489_VehiclePlateNumberReserve")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100489_VehiclePlateNumberReserve", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100489VehiclePlateNumberReserve")
    @ResponseWrapper(localName = "WS100489_VehiclePlateNumberReserveResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100489VehiclePlateNumberReserveResponse")
    public ServiceResponse ws100489VehiclePlateNumberReserve(
        @WebParam(name = "request", targetNamespace = "")
        VehiclePlateNumberReserveRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100404_getECDataInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100404_getECDataInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100404GetECDataInfo")
    @ResponseWrapper(localName = "WS100404_getECDataInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100404GetECDataInfoResponse")
    public ServiceResponse ws100404GetECDataInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetECDataRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100479_CheckBorderPermitVehicle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100479_CheckBorderPermitVehicle", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100479CheckBorderPermitVehicle")
    @ResponseWrapper(localName = "WS100479_CheckBorderPermitVehicleResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100479CheckBorderPermitVehicleResponse")
    public ServiceResponse ws100479CheckBorderPermitVehicle(
        @WebParam(name = "request", targetNamespace = "")
        CheckBorderPermitVehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100422_getCitizenPenaltyList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100422_getCitizenPenaltyList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100422GetCitizenPenaltyList")
    @ResponseWrapper(localName = "WS100422_getCitizenPenaltyListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100422GetCitizenPenaltyListResponse")
    public ServiceResponse ws100422GetCitizenPenaltyList(
        @WebParam(name = "request", targetNamespace = "")
        CitizenPenaltyListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100414_getImportExportItemList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100414_getImportExportItemList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100414GetImportExportItemList")
    @ResponseWrapper(localName = "WS100414_getImportExportItemListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100414GetImportExportItemListResponse")
    public ServiceResponse ws100414GetImportExportItemList(
        @WebParam(name = "request", targetNamespace = "")
        GetImportExportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100441_umnsVehicleInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100441_umnsVehicleInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100441UmnsVehicleInfo")
    @ResponseWrapper(localName = "WS100441_umnsVehicleInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100441UmnsVehicleInfoResponse")
    public ServiceResponse ws100441UmnsVehicleInfo(
        @WebParam(name = "request", targetNamespace = "")
        RegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100461_MandatoryInsuranceCaseStatementList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100461_MandatoryInsuranceCaseStatementList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100461MandatoryInsuranceCaseStatementList")
    @ResponseWrapper(localName = "WS100461_MandatoryInsuranceCaseStatementListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100461MandatoryInsuranceCaseStatementListResponse")
    public ServiceResponse ws100461MandatoryInsuranceCaseStatementList(
        @WebParam(name = "request", targetNamespace = "")
        MandatoryInsuranceCaseListRequestData request);

    /**
     * 
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100445_driverLicenseOrderedLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100445_driverLicenseOrderedLog", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100445DriverLicenseOrderedLog")
    @ResponseWrapper(localName = "WS100445_driverLicenseOrderedLogResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100445DriverLicenseOrderedLogResponse")
    public ServiceResponse ws100445DriverLicenseOrderedLog();

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100436_vehicleLegalEntityInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100436_vehicleLegalEntityInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100436VehicleLegalEntityInfo")
    @ResponseWrapper(localName = "WS100436_vehicleLegalEntityInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100436VehicleLegalEntityInfoResponse")
    public ServiceResponse ws100436VehicleLegalEntityInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleLegalEntityInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100471_TrainBorderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100471_TrainBorderInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100471TrainBorderInfo")
    @ResponseWrapper(localName = "WS100471_TrainBorderInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100471TrainBorderInfoResponse")
    public ServiceResponse ws100471TrainBorderInfo(
        @WebParam(name = "request", targetNamespace = "")
        TrainBorderInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100474_GetBusDispatcherList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100474_GetBusDispatcherList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100474GetBusDispatcherList")
    @ResponseWrapper(localName = "WS100474_GetBusDispatcherListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100474GetBusDispatcherListResponse")
    public ServiceResponse ws100474GetBusDispatcherList(
        @WebParam(name = "request", targetNamespace = "")
        GetBusDispatcherListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100444_orderDriverLicense")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100444_orderDriverLicense", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100444OrderDriverLicense")
    @ResponseWrapper(localName = "WS100444_orderDriverLicenseResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100444OrderDriverLicenseResponse")
    public ServiceResponse ws100444OrderDriverLicense(
        @WebParam(name = "request", targetNamespace = "")
        OrderDriverLicenseRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100406_getCitizenVehicleList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100406_getCitizenVehicleList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100406GetCitizenVehicleList")
    @ResponseWrapper(localName = "WS100406_getCitizenVehicleListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100406GetCitizenVehicleListResponse")
    public ServiceResponse ws100406GetCitizenVehicleList(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100412_getTransportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100412_getTransportInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100412GetTransportInfo")
    @ResponseWrapper(localName = "WS100412_getTransportInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100412GetTransportInfoResponse")
    public ServiceResponse ws100412GetTransportInfo(
        @WebParam(name = "request", targetNamespace = "")
        TransportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100411_vehicleImportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100411_vehicleImportInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100411VehicleImportInfo")
    @ResponseWrapper(localName = "WS100411_vehicleImportInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100411VehicleImportInfoResponse")
    public ServiceResponse ws100411VehicleImportInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleImportInfoData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100420_getOrganizationVehicleList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100420_getOrganizationVehicleList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100420GetOrganizationVehicleList")
    @ResponseWrapper(localName = "WS100420_getOrganizationVehicleListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100420GetOrganizationVehicleListResponse")
    public ServiceResponse ws100420GetOrganizationVehicleList(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleOrganizationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100429_transportConclutionResponseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100429_transportConclutionResponseInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100429TransportConclutionResponseInfo")
    @ResponseWrapper(localName = "WS100429_transportConclutionResponseInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100429TransportConclutionResponseInfoResponse")
    public ServiceResponse ws100429TransportConclutionResponseInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetECDataRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100451_VerifyPaymentInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100451_VerifyPaymentInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100451VerifyPaymentInfo")
    @ResponseWrapper(localName = "WS100451_VerifyPaymentInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100451VerifyPaymentInfoResponse")
    public ServiceResponse ws100451VerifyPaymentInfo(
        @WebParam(name = "request", targetNamespace = "")
        VerifyPaymentInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100421_getPreOwnedVehicle")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100421_getPreOwnedVehicle", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100421GetPreOwnedVehicle")
    @ResponseWrapper(localName = "WS100421_getPreOwnedVehicleResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100421GetPreOwnedVehicleResponse")
    public ServiceResponse ws100421GetPreOwnedVehicle(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100481_GetSavedNumberList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100481_GetSavedNumberList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100481GetSavedNumberList")
    @ResponseWrapper(localName = "WS100481_GetSavedNumberListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100481GetSavedNumberListResponse")
    public ServiceResponse ws100481GetSavedNumberList(
        @WebParam(name = "request", targetNamespace = "")
        GetSavedNumberListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100493_ReportTotalPassenger")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100493_ReportTotalPassenger", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100493ReportTotalPassenger")
    @ResponseWrapper(localName = "WS100493_ReportTotalPassengerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100493ReportTotalPassengerResponse")
    public ServiceResponse ws100493ReportTotalPassenger(
        @WebParam(name = "request", targetNamespace = "")
        ReportTotalTripRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100437_vehicleLegalEntityTotal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100437_vehicleLegalEntityTotal", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100437VehicleLegalEntityTotal")
    @ResponseWrapper(localName = "WS100437_vehicleLegalEntityTotalResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100437VehicleLegalEntityTotalResponse")
    public ServiceResponse ws100437VehicleLegalEntityTotal(
        @WebParam(name = "request", targetNamespace = "")
        OrgRegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100476_BorderRegisteredPassengers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100476_BorderRegisteredPassengers", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100476BorderRegisteredPassengers")
    @ResponseWrapper(localName = "WS100476_BorderRegisteredPassengersResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100476BorderRegisteredPassengersResponse")
    public ServiceResponse ws100476BorderRegisteredPassengers(
        @WebParam(name = "request", targetNamespace = "")
        BorderRegisteredPassengersInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100438_getPreOwnedOrgVehicleTotal")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100438_getPreOwnedOrgVehicleTotal", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100438GetPreOwnedOrgVehicleTotal")
    @ResponseWrapper(localName = "WS100438_getPreOwnedOrgVehicleTotalResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100438GetPreOwnedOrgVehicleTotalResponse")
    public ServiceResponse ws100438GetPreOwnedOrgVehicleTotal(
        @WebParam(name = "request", targetNamespace = "")
        OrgRegnumRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100402_getVehicleOwnerHistoryList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100402_getVehicleOwnerHistoryList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100402GetVehicleOwnerHistoryList")
    @ResponseWrapper(localName = "WS100402_getVehicleOwnerHistoryListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100402GetVehicleOwnerHistoryListResponse")
    public ServiceResponse ws100402GetVehicleOwnerHistoryList(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100488_SavePlateNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100488_SavePlateNumber", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100488SavePlateNumber")
    @ResponseWrapper(localName = "WS100488_SavePlateNumberResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100488SavePlateNumberResponse")
    public ServiceResponse ws100488SavePlateNumber(
        @WebParam(name = "request", targetNamespace = "")
        SavePlateNumberRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100435_getPreOwnedVehicleWithOrgRegnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100435_getPreOwnedVehicleWithOrgRegnum", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100435GetPreOwnedVehicleWithOrgRegnum")
    @ResponseWrapper(localName = "WS100435_getPreOwnedVehicleWithOrgRegnumResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100435GetPreOwnedVehicleWithOrgRegnumResponse")
    public ServiceResponse ws100435GetPreOwnedVehicleWithOrgRegnum(
        @WebParam(name = "request", targetNamespace = "")
        VehicleLegalEntityInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100475_GetBusLocation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100475_GetBusLocation", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100475GetBusLocation")
    @ResponseWrapper(localName = "WS100475_GetBusLocationResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100475GetBusLocationResponse")
    public ServiceResponse ws100475GetBusLocation(
        @WebParam(name = "request", targetNamespace = "")
        GetBusLocationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100452_VehicleOwnershipTransferVerification")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100452_VehicleOwnershipTransferVerification", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100452VehicleOwnershipTransferVerification")
    @ResponseWrapper(localName = "WS100452_VehicleOwnershipTransferVerificationResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100452VehicleOwnershipTransferVerificationResponse")
    public ServiceResponse ws100452VehicleOwnershipTransferVerification(
        @WebParam(name = "request", targetNamespace = "")
        VehicleOwnershipTransferVerificationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100416_getOwnerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100416_getOwnerInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100416GetOwnerInfo")
    @ResponseWrapper(localName = "WS100416_getOwnerInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100416GetOwnerInfoResponse")
    public ServiceResponse ws100416GetOwnerInfo(
        @WebParam(name = "request", targetNamespace = "")
        OwnerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100467_FreightTransportTrainDocumentList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100467_FreightTransportTrainDocumentList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100467FreightTransportTrainDocumentList")
    @ResponseWrapper(localName = "WS100467_FreightTransportTrainDocumentListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100467FreightTransportTrainDocumentListResponse")
    public ServiceResponse ws100467FreightTransportTrainDocumentList(
        @WebParam(name = "request", targetNamespace = "")
        FreightTransportTrainDocListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS101401_VehicleTaxInfoService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS101401_VehicleTaxInfoService", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS101401VehicleTaxInfoService")
    @ResponseWrapper(localName = "WS101401_VehicleTaxInfoServiceResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS101401VehicleTaxInfoServiceResponse")
    public ServiceResponse ws101401VehicleTaxInfoService(
        @WebParam(name = "request", targetNamespace = "")
        VehicleTaxInfoServiceRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100470_VehicleBorderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100470_VehicleBorderInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100470VehicleBorderInfo")
    @ResponseWrapper(localName = "WS100470_VehicleBorderInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100470VehicleBorderInfoResponse")
    public ServiceResponse ws100470VehicleBorderInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100403_getVehiclePenaltyList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100403_getVehiclePenaltyList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100403GetVehiclePenaltyList")
    @ResponseWrapper(localName = "WS100403_getVehiclePenaltyListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100403GetVehiclePenaltyListResponse")
    public ServiceResponse ws100403GetVehiclePenaltyList(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehiclePenaltyInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100430_transportConflictInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100430_transportConflictInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100430TransportConflictInfo")
    @ResponseWrapper(localName = "WS100430_transportConflictInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100430TransportConflictInfoResponse")
    public ServiceResponse ws100430TransportConflictInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetECDataRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100454_GetDriverInfoWithRegisterAndLicense")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100454_GetDriverInfoWithRegisterAndLicense", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100454GetDriverInfoWithRegisterAndLicense")
    @ResponseWrapper(localName = "WS100454_GetDriverInfoWithRegisterAndLicenseResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100454GetDriverInfoWithRegisterAndLicenseResponse")
    public ServiceResponse ws100454GetDriverInfoWithRegisterAndLicense(
        @WebParam(name = "request", targetNamespace = "")
        ServiceDriverLicenseInfoData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100407_getDriverLicenseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100407_getDriverLicenseInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100407GetDriverLicenseInfo")
    @ResponseWrapper(localName = "WS100407_getDriverLicenseInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100407GetDriverLicenseInfoResponse")
    public ServiceResponse ws100407GetDriverLicenseInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceDriverLicenseInfoData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100418_vehicleLimitedInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100418_vehicleLimitedInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100418VehicleLimitedInfo")
    @ResponseWrapper(localName = "WS100418_vehicleLimitedInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100418VehicleLimitedInfoResponse")
    public ServiceResponse ws100418VehicleLimitedInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleLimitedRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100447_technicalReviewDirectory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100447_technicalReviewDirectory", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100447TechnicalReviewDirectory")
    @ResponseWrapper(localName = "WS100447_technicalReviewDirectoryResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100447TechnicalReviewDirectoryResponse")
    public ServiceResponse ws100447TechnicalReviewDirectory(
        @WebParam(name = "request", targetNamespace = "")
        OwnerWaterWayVechicleDirectoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100415_vehicleInfoList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100415_vehicleInfoList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100415VehicleInfoList")
    @ResponseWrapper(localName = "WS100415_vehicleInfoListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100415VehicleInfoListResponse")
    public ServiceResponse ws100415VehicleInfoList(
        @WebParam(name = "request", targetNamespace = "")
        VehicleListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100462_TransportCompanyList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100462_TransportCompanyList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100462TransportCompanyList")
    @ResponseWrapper(localName = "WS100462_TransportCompanyListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100462TransportCompanyListResponse")
    public ServiceResponse ws100462TransportCompanyList(
        @WebParam(name = "request", targetNamespace = "")
        TransportCompanyListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100440_payInvoice")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100440_payInvoice", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100440PayInvoice")
    @ResponseWrapper(localName = "WS100440_payInvoiceResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100440PayInvoiceResponse")
    public ServiceResponse ws100440PayInvoice(
        @WebParam(name = "request", targetNamespace = "")
        PayInvoiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100455_TollInvoiceDetails")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100455_TollInvoiceDetails", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100455TollInvoiceDetails")
    @ResponseWrapper(localName = "WS100455_TollInvoiceDetailsResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100455TollInvoiceDetailsResponse")
    public ServiceResponse ws100455TollInvoiceDetails(
        @WebParam(name = "request", targetNamespace = "")
        TollInvoiceDetailsRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100466_TransportCompanyCreateWorker")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100466_TransportCompanyCreateWorker", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100466TransportCompanyCreateWorker")
    @ResponseWrapper(localName = "WS100466_TransportCompanyCreateWorkerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100466TransportCompanyCreateWorkerResponse")
    public ServiceResponse ws100466TransportCompanyCreateWorker(
        @WebParam(name = "request", targetNamespace = "")
        TransportCompanyCreateWorkerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100423_borderRegisteredTransportInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100423_borderRegisteredTransportInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100423BorderRegisteredTransportInfo")
    @ResponseWrapper(localName = "WS100423_borderRegisteredTransportInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100423BorderRegisteredTransportInfoResponse")
    public ServiceResponse ws100423BorderRegisteredTransportInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100460_MandatoryInsuranceCaseList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100460_MandatoryInsuranceCaseList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100460MandatoryInsuranceCaseList")
    @ResponseWrapper(localName = "WS100460_MandatoryInsuranceCaseListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100460MandatoryInsuranceCaseListResponse")
    public ServiceResponse ws100460MandatoryInsuranceCaseList(
        @WebParam(name = "request", targetNamespace = "")
        MandatoryInsuranceCaseListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100477_BorderRegisteredTransport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100477_BorderRegisteredTransport", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100477BorderRegisteredTransport")
    @ResponseWrapper(localName = "WS100477_BorderRegisteredTransportResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100477BorderRegisteredTransportResponse")
    public ServiceResponse ws100477BorderRegisteredTransport(
        @WebParam(name = "request", targetNamespace = "")
        BorderRegisteredTransportInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100419_vehicleBorderPass")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100419_vehicleBorderPass", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100419VehicleBorderPass")
    @ResponseWrapper(localName = "WS100419_vehicleBorderPassResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100419VehicleBorderPassResponse")
    public ServiceResponse ws100419VehicleBorderPass(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100486_CheckVehicleOwnerRegistration")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100486_CheckVehicleOwnerRegistration", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100486CheckVehicleOwnerRegistration")
    @ResponseWrapper(localName = "WS100486_CheckVehicleOwnerRegistrationResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100486CheckVehicleOwnerRegistrationResponse")
    public ServiceResponse ws100486CheckVehicleOwnerRegistration(
        @WebParam(name = "request", targetNamespace = "")
        CheckVehicleOwnerRegistrationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100458_MandatoryInsuranceShortList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100458_MandatoryInsuranceShortList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100458MandatoryInsuranceShortList")
    @ResponseWrapper(localName = "WS100458_MandatoryInsuranceShortListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100458MandatoryInsuranceShortListResponse")
    public ServiceResponse ws100458MandatoryInsuranceShortList(
        @WebParam(name = "request", targetNamespace = "")
        MandatoryInsuranceShortListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100468_FreightTransportTrainDocumentDetail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100468_FreightTransportTrainDocumentDetail", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100468FreightTransportTrainDocumentDetail")
    @ResponseWrapper(localName = "WS100468_FreightTransportTrainDocumentDetailResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100468FreightTransportTrainDocumentDetailResponse")
    public ServiceResponse ws100468FreightTransportTrainDocumentDetail(
        @WebParam(name = "request", targetNamespace = "")
        FreightTransportTrainDocDetailRequestData request);

    /**
     * 
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100442_driverLicenseExpireSoonLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100442_driverLicenseExpireSoonLog", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100442DriverLicenseExpireSoonLog")
    @ResponseWrapper(localName = "WS100442_driverLicenseExpireSoonLogResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100442DriverLicenseExpireSoonLogResponse")
    public ServiceResponse ws100442DriverLicenseExpireSoonLog();

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100478_CheckPassenger")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100478_CheckPassenger", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100478CheckPassenger")
    @ResponseWrapper(localName = "WS100478_CheckPassengerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100478CheckPassengerResponse")
    public ServiceResponse ws100478CheckPassenger(
        @WebParam(name = "request", targetNamespace = "")
        CheckPassengerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100490_RegisterPlateNumberOwner")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100490_RegisterPlateNumberOwner", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100490RegisterPlateNumberOwner")
    @ResponseWrapper(localName = "WS100490_RegisterPlateNumberOwnerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100490RegisterPlateNumberOwnerResponse")
    public ServiceResponse ws100490RegisterPlateNumberOwner(
        @WebParam(name = "request", targetNamespace = "")
        RegisterPlateNumberOwnerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100432_getVehicleInspectionDataByPlateNo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100432_getVehicleInspectionDataByPlateNo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100432GetVehicleInspectionDataByPlateNo")
    @ResponseWrapper(localName = "WS100432_getVehicleInspectionDataByPlateNoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100432GetVehicleInspectionDataByPlateNoResponse")
    public ServiceResponse ws100432GetVehicleInspectionDataByPlateNo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleInspectionByPlateNoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100499_ProductList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100499_ProductList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100499ProductList")
    @ResponseWrapper(localName = "WS100499_ProductListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100499ProductListResponse")
    public ServiceResponse ws100499ProductList(
        @WebParam(name = "request", targetNamespace = "")
        ProductListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100410_isVehicleCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100410_isVehicleCheck", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100410IsVehicleCheck")
    @ResponseWrapper(localName = "WS100410_isVehicleCheckResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100410IsVehicleCheckResponse")
    public ServiceResponse ws100410IsVehicleCheck(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100424_borderRegisteredPassengerInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100424_borderRegisteredPassengerInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100424BorderRegisteredPassengerInfo")
    @ResponseWrapper(localName = "WS100424_borderRegisteredPassengerInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100424BorderRegisteredPassengerInfoResponse")
    public ServiceResponse ws100424BorderRegisteredPassengerInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorderPassRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100483_GetAvailableNumberList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100483_GetAvailableNumberList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100483GetAvailableNumberList")
    @ResponseWrapper(localName = "WS100483_GetAvailableNumberListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100483GetAvailableNumberListResponse")
    public ServiceResponse ws100483GetAvailableNumberList(
        @WebParam(name = "request", targetNamespace = "")
        GetAvailableNumberListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100469_SasCompanyInfoList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100469_SasCompanyInfoList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100469SasCompanyInfoList")
    @ResponseWrapper(localName = "WS100469_SasCompanyInfoListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100469SasCompanyInfoListResponse")
    public ServiceResponse ws100469SasCompanyInfoList(
        @WebParam(name = "request", targetNamespace = "")
        SasCompanyInfoListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100439_unpaidInvoiceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100439_unpaidInvoiceInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100439UnpaidInvoiceInfo")
    @ResponseWrapper(localName = "WS100439_unpaidInvoiceInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100439UnpaidInvoiceInfoResponse")
    public ServiceResponse ws100439UnpaidInvoiceInfo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenPenaltyListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100427_transportOrganizationCarsInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100427_transportOrganizationCarsInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100427TransportOrganizationCarsInfo")
    @ResponseWrapper(localName = "WS100427_transportOrganizationCarsInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100427TransportOrganizationCarsInfoResponse")
    public ServiceResponse ws100427TransportOrganizationCarsInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleOrganizationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100459_MandatoryInsuranceDetailList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100459_MandatoryInsuranceDetailList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100459MandatoryInsuranceDetailList")
    @ResponseWrapper(localName = "WS100459_MandatoryInsuranceDetailListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100459MandatoryInsuranceDetailListResponse")
    public ServiceResponse ws100459MandatoryInsuranceDetailList(
        @WebParam(name = "request", targetNamespace = "")
        MandatoryInsuranceDetailListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100497_PoliceECLicenseChecker")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100497_PoliceECLicenseChecker", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100497PoliceECLicenseChecker")
    @ResponseWrapper(localName = "WS100497_PoliceECLicenseCheckerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100497PoliceECLicenseCheckerResponse")
    public ServiceResponse ws100497PoliceECLicenseChecker(
        @WebParam(name = "request", targetNamespace = "")
        PoliceECLicenseCheckerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100401_getVehicleInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100401_getVehicleInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100401GetVehicleInfo")
    @ResponseWrapper(localName = "WS100401_getVehicleInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100401GetVehicleInfoResponse")
    public ServiceResponse ws100401GetVehicleInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100473_GetBusDirectionList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100473_GetBusDirectionList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100473GetBusDirectionList")
    @ResponseWrapper(localName = "WS100473_GetBusDirectionListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100473GetBusDirectionListResponse")
    public ServiceResponse ws100473GetBusDirectionList(
        @WebParam(name = "request", targetNamespace = "")
        GetBusDirectionListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100448_drivingRightsDirectory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100448_drivingRightsDirectory", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100448DrivingRightsDirectory")
    @ResponseWrapper(localName = "WS100448_drivingRightsDirectoryResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100448DrivingRightsDirectoryResponse")
    public ServiceResponse ws100448DrivingRightsDirectory(
        @WebParam(name = "request", targetNamespace = "")
        CitizenPenaltyListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100465_TransportCompanyRouteList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100465_TransportCompanyRouteList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100465TransportCompanyRouteList")
    @ResponseWrapper(localName = "WS100465_TransportCompanyRouteListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100465TransportCompanyRouteListResponse")
    public ServiceResponse ws100465TransportCompanyRouteList(
        @WebParam(name = "request", targetNamespace = "")
        TransportCompanyRouteListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100446_ownerWaterWayVechicleDirectory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100446_ownerWaterWayVechicleDirectory", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100446OwnerWaterWayVechicleDirectory")
    @ResponseWrapper(localName = "WS100446_ownerWaterWayVechicleDirectoryResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100446OwnerWaterWayVechicleDirectoryResponse")
    public ServiceResponse ws100446OwnerWaterWayVechicleDirectory(
        @WebParam(name = "request", targetNamespace = "")
        OwnerWaterWayVechicleDirectoryRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100434_checkECLIcenseFromKiosk")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100434_checkECLIcenseFromKiosk", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100434CheckECLIcenseFromKiosk")
    @ResponseWrapper(localName = "WS100434_checkECLIcenseFromKioskResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100434CheckECLIcenseFromKioskResponse")
    public ServiceResponse ws100434CheckECLIcenseFromKiosk(
        @WebParam(name = "request", targetNamespace = "")
        CheckECLIcenseFromKioskRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100428_transportCheckGPSPayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100428_transportCheckGPSPayment", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100428TransportCheckGPSPayment")
    @ResponseWrapper(localName = "WS100428_transportCheckGPSPaymentResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100428TransportCheckGPSPaymentResponse")
    public ServiceResponse ws100428TransportCheckGPSPayment(
        @WebParam(name = "request", targetNamespace = "")
        TransportCheckGPSPaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100463_TransportCompanyVehiclesList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100463_TransportCompanyVehiclesList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100463TransportCompanyVehiclesList")
    @ResponseWrapper(localName = "WS100463_TransportCompanyVehiclesListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100463TransportCompanyVehiclesListResponse")
    public ServiceResponse ws100463TransportCompanyVehiclesList(
        @WebParam(name = "request", targetNamespace = "")
        TransportCompanyVehiclesListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100485_PlateNumberAffiliation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100485_PlateNumberAffiliation", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100485PlateNumberAffiliation")
    @ResponseWrapper(localName = "WS100485_PlateNumberAffiliationResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100485PlateNumberAffiliationResponse")
    public ServiceResponse ws100485PlateNumberAffiliation(
        @WebParam(name = "request", targetNamespace = "")
        PlateNumberAffiliationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100464_TransportCompanyEmployeeList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100464_TransportCompanyEmployeeList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100464TransportCompanyEmployeeList")
    @ResponseWrapper(localName = "WS100464_TransportCompanyEmployeeListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100464TransportCompanyEmployeeListResponse")
    public ServiceResponse ws100464TransportCompanyEmployeeList(
        @WebParam(name = "request", targetNamespace = "")
        TransportCompanyEmployeeListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100417_specialDriverInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100417_specialDriverInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100417SpecialDriverInfo")
    @ResponseWrapper(localName = "WS100417_specialDriverInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100417SpecialDriverInfoResponse")
    public ServiceResponse ws100417SpecialDriverInfo(
        @WebParam(name = "request", targetNamespace = "")
        SpecialDriverRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100405_getVehicleTaxInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100405_getVehicleTaxInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100405GetVehicleTaxInfo")
    @ResponseWrapper(localName = "WS100405_getVehicleTaxInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100405GetVehicleTaxInfoResponse")
    public ServiceResponse ws100405GetVehicleTaxInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100498_ECLicenseCancel")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100498_ECLicenseCancel", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100498ECLicenseCancel")
    @ResponseWrapper(localName = "WS100498_ECLicenseCancelResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100498ECLicenseCancelResponse")
    public ServiceResponse ws100498ECLicenseCancel(
        @WebParam(name = "request", targetNamespace = "")
        EcLicenseCancelRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100480_VehicleAndDriverBorderReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100480_VehicleAndDriverBorderReport", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100480VehicleAndDriverBorderReport")
    @ResponseWrapper(localName = "WS100480_VehicleAndDriverBorderReportResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100480VehicleAndDriverBorderReportResponse")
    public ServiceResponse ws100480VehicleAndDriverBorderReport(
        @WebParam(name = "request", targetNamespace = "")
        VehicleAndDriverBorderReportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100408_updatePenaltyPayment")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100408_updatePenaltyPayment", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100408UpdatePenaltyPayment")
    @ResponseWrapper(localName = "WS100408_updatePenaltyPaymentResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100408UpdatePenaltyPaymentResponse")
    public ServiceResponse ws100408UpdatePenaltyPayment(
        @WebParam(name = "request", targetNamespace = "")
        ServiceUpdatePenaltyPaymentRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100472_PlateBorderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100472_PlateBorderInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100472PlateBorderInfo")
    @ResponseWrapper(localName = "WS100472_PlateBorderInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100472PlateBorderInfoResponse")
    public ServiceResponse ws100472PlateBorderInfo(
        @WebParam(name = "request", targetNamespace = "")
        PlateBorderInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100457_GetInternationalDriverInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100457_GetInternationalDriverInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100457GetInternationalDriverInfo")
    @ResponseWrapper(localName = "WS100457_GetInternationalDriverInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100457GetInternationalDriverInfoResponse")
    public ServiceResponse ws100457GetInternationalDriverInfo(
        @WebParam(name = "request", targetNamespace = "")
        GetInternationalDriverInfoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100487_OwnerVehicleList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100487_OwnerVehicleList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100487OwnerVehicleList")
    @ResponseWrapper(localName = "WS100487_OwnerVehicleListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100487OwnerVehicleListResponse")
    public ServiceResponse ws100487OwnerVehicleList(
        @WebParam(name = "request", targetNamespace = "")
        OwnerVehicleListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100409_getVehicleInspectionInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100409_getVehicleInspectionInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100409GetVehicleInspectionInfo")
    @ResponseWrapper(localName = "WS100409_getVehicleInspectionInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100409GetVehicleInspectionInfoResponse")
    public ServiceResponse ws100409GetVehicleInspectionInfo(
        @WebParam(name = "request", targetNamespace = "")
        VehicleInspectionRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100495_ECLicenseCreator")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100495_ECLicenseCreator", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100495ECLicenseCreator")
    @ResponseWrapper(localName = "WS100495_ECLicenseCreatorResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100495ECLicenseCreatorResponse")
    public ServiceResponse ws100495ECLicenseCreator(
        @WebParam(name = "request", targetNamespace = "")
        EcLicenseCreatorRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100453_VehicleBorrowCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100453_VehicleBorrowCheck", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100453VehicleBorrowCheck")
    @ResponseWrapper(localName = "WS100453_VehicleBorrowCheckResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100453VehicleBorrowCheckResponse")
    public ServiceResponse ws100453VehicleBorrowCheck(
        @WebParam(name = "request", targetNamespace = "")
        VehicleBorrowCheckRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100484_NumberSaveAvailability")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100484_NumberSaveAvailability", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100484NumberSaveAvailability")
    @ResponseWrapper(localName = "WS100484_NumberSaveAvailabilityResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100484NumberSaveAvailabilityResponse")
    public ServiceResponse ws100484NumberSaveAvailability(
        @WebParam(name = "request", targetNamespace = "")
        NumberSaveAvailabilityRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100449_vehicleCertificate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100449_vehicleCertificate", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100449VehicleCertificate")
    @ResponseWrapper(localName = "WS100449_vehicleCertificateResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100449VehicleCertificateResponse")
    public ServiceResponse ws100449VehicleCertificate(
        @WebParam(name = "request", targetNamespace = "")
        VehicleCertRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100425_getImportExportItemExpandList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100425_getImportExportItemExpandList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100425GetImportExportItemExpandList")
    @ResponseWrapper(localName = "WS100425_getImportExportItemExpandListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100425GetImportExportItemExpandListResponse")
    public ServiceResponse ws100425GetImportExportItemExpandList(
        @WebParam(name = "request", targetNamespace = "")
        GetImportExportRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100431_permittedVehiclesList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100431_permittedVehiclesList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100431PermittedVehiclesList")
    @ResponseWrapper(localName = "WS100431_permittedVehiclesListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100431PermittedVehiclesListResponse")
    public ServiceResponse ws100431PermittedVehiclesList(
        @WebParam(name = "request", targetNamespace = "")
        PermittedVehiclesListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100413_getInternationalDriverLicenseInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100413_getInternationalDriverLicenseInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100413GetInternationalDriverLicenseInfo")
    @ResponseWrapper(localName = "WS100413_getInternationalDriverLicenseInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100413GetInternationalDriverLicenseInfoResponse")
    public ServiceResponse ws100413GetInternationalDriverLicenseInfo(
        @WebParam(name = "request", targetNamespace = "")
        InternationalDriverLicenseRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100450_VehicleOwnershipTransfer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100450_VehicleOwnershipTransfer", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100450VehicleOwnershipTransfer")
    @ResponseWrapper(localName = "WS100450_VehicleOwnershipTransferResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100450VehicleOwnershipTransferResponse")
    public ServiceResponse ws100450VehicleOwnershipTransfer(
        @WebParam(name = "request", targetNamespace = "")
        VehicleOwnershipTransferRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100433_unlicensedVehiclesList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100433_unlicensedVehiclesList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100433UnlicensedVehiclesList")
    @ResponseWrapper(localName = "WS100433_unlicensedVehiclesListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100433UnlicensedVehiclesListResponse")
    public ServiceResponse ws100433UnlicensedVehiclesList(
        @WebParam(name = "request", targetNamespace = "")
        PermittedVehiclesListRequestData request);

    /**
     * 
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100443_driverLicenseExpiredLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100443_driverLicenseExpiredLog", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100443DriverLicenseExpiredLog")
    @ResponseWrapper(localName = "WS100443_driverLicenseExpiredLogResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100443DriverLicenseExpiredLogResponse")
    public ServiceResponse ws100443DriverLicenseExpiredLog();

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100491_TransferPlateNumberOwner")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100491_TransferPlateNumberOwner", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100491TransferPlateNumberOwner")
    @ResponseWrapper(localName = "WS100491_TransferPlateNumberOwnerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100491TransferPlateNumberOwnerResponse")
    public ServiceResponse ws100491TransferPlateNumberOwner(
        @WebParam(name = "request", targetNamespace = "")
        TransferPlateNumberOwnerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100496_ECLicenseChecker")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100496_ECLicenseChecker", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100496ECLicenseChecker")
    @ResponseWrapper(localName = "WS100496_ECLicenseCheckerResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100496ECLicenseCheckerResponse")
    public ServiceResponse ws100496ECLicenseChecker(
        @WebParam(name = "request", targetNamespace = "")
        EcLicenseCheckerRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100426_transportGetOrganizationInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100426_transportGetOrganizationInfo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100426TransportGetOrganizationInfo")
    @ResponseWrapper(localName = "WS100426_transportGetOrganizationInfoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100426TransportGetOrganizationInfoResponse")
    public ServiceResponse ws100426TransportGetOrganizationInfo(
        @WebParam(name = "request", targetNamespace = "")
        ServiceVehicleOrganizationRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100482_GetReservedNumberList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100482_GetReservedNumberList", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100482GetReservedNumberList")
    @ResponseWrapper(localName = "WS100482_GetReservedNumberListResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100482GetReservedNumberListResponse")
    public ServiceResponse ws100482GetReservedNumberList(
        @WebParam(name = "request", targetNamespace = "")
        GetReservedNumberListRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100456_GetFineInfoUsingFineNumber")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100456_GetFineInfoUsingFineNumber", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100456GetFineInfoUsingFineNumber")
    @ResponseWrapper(localName = "WS100456_GetFineInfoUsingFineNumberResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100456GetFineInfoUsingFineNumberResponse")
    public ServiceResponse ws100456GetFineInfoUsingFineNumber(
        @WebParam(name = "request", targetNamespace = "")
        GetFineInfoUsingFineNumberRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100492_ReportTotalTrip")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100492_ReportTotalTrip", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100492ReportTotalTrip")
    @ResponseWrapper(localName = "WS100492_ReportTotalTripResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100492ReportTotalTripResponse")
    public ServiceResponse ws100492ReportTotalTrip(
        @WebParam(name = "request", targetNamespace = "")
        ReportTotalTripRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.transport.ServiceResponse
     */
    @WebMethod(operationName = "WS100494_UnpaidInvoiceInfoByPlateNo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100494_UnpaidInvoiceInfoByPlateNo", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100494UnpaidInvoiceInfoByPlateNo")
    @ResponseWrapper(localName = "WS100494_UnpaidInvoiceInfoByPlateNoResponse", targetNamespace = "http://transport.xyp.gov.mn/", className = "mn.gov.xyp.transport.WS100494UnpaidInvoiceInfoByPlateNoResponse")
    public ServiceResponse ws100494UnpaidInvoiceInfoByPlateNo(
        @WebParam(name = "request", targetNamespace = "")
        CitizenPenaltyListRequestData request);

}
