
package mn.gov.xyp.meta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MetaService", targetNamespace = "http://meta.xyp.gov.mn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetaService {


    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100011_checkOtpByCitizen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100011_checkOtpByCitizen", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100011CheckOtpByCitizen")
    @ResponseWrapper(localName = "WS100011_checkOtpByCitizenResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100011CheckOtpByCitizenResponse")
    public ServiceResponse ws100011CheckOtpByCitizen(
        @WebParam(name = "request", targetNamespace = "")
        CheckOtpByCitizenRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100006_checkAccess")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100006_checkAccess", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100006CheckAccess")
    @ResponseWrapper(localName = "WS100006_checkAccessResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100006CheckAccessResponse")
    public ServiceResponse ws100006CheckAccess(
        @WebParam(name = "request", targetNamespace = "")
        AclRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100014_authServiceByCitizen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100014_authServiceByCitizen", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100014AuthServiceByCitizen")
    @ResponseWrapper(localName = "WS100014_authServiceByCitizenResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100014AuthServiceByCitizenResponse")
    public ServiceResponse ws100014AuthServiceByCitizen(
        @WebParam(name = "request", targetNamespace = "")
        AuthServiceByCitizenRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100017_logCheck")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100017_logCheck", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100017LogCheck")
    @ResponseWrapper(localName = "WS100017_logCheckResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100017LogCheckResponse")
    public ServiceResponse ws100017LogCheck(
        @WebParam(name = "request", targetNamespace = "")
        LogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100018_GetGsignPhoneNo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100018_GetGsignPhoneNo", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100018GetGsignPhoneNo")
    @ResponseWrapper(localName = "WS100018_GetGsignPhoneNoResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100018GetGsignPhoneNoResponse")
    public ServiceResponse ws100018GetGsignPhoneNo(
        @WebParam(name = "request", targetNamespace = "")
        GetGsignPhoneNoRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100003_getLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100003_getLog", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100003GetLog")
    @ResponseWrapper(localName = "WS100003_getLogResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100003GetLogResponse")
    public ServiceResponse ws100003GetLog(
        @WebParam(name = "request", targetNamespace = "")
        LogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100019_SsoRegisterOtp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100019_SsoRegisterOtp", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100019SsoRegisterOtp")
    @ResponseWrapper(localName = "WS100019_SsoRegisterOtpResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100019SsoRegisterOtpResponse")
    public ServiceResponse ws100019SsoRegisterOtp(
        @WebParam(name = "request", targetNamespace = "")
        SsoRegisterOtpRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100002_mock")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100002_mock", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100002Mock")
    @ResponseWrapper(localName = "WS100002_mockResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100002MockResponse")
    public ServiceResponse ws100002Mock(
        @WebParam(name = "request", targetNamespace = "")
        MockRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100009_checkOtp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100009_checkOtp", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100009CheckOtp")
    @ResponseWrapper(localName = "WS100009_checkOtpResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100009CheckOtpResponse")
    public ServiceResponse ws100009CheckOtp(
        @WebParam(name = "request", targetNamespace = "")
        CheckOtpRequestData request);

    /**
     * 
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100001_listAccess")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100001_listAccess", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100001ListAccess")
    @ResponseWrapper(localName = "WS100001_listAccessResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100001ListAccessResponse")
    public ServiceResponse ws100001ListAccess();

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100013_authServiceCheckByOtp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100013_authServiceCheckByOtp", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100013AuthServiceCheckByOtp")
    @ResponseWrapper(localName = "WS100013_authServiceCheckByOtpResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100013AuthServiceCheckByOtpResponse")
    public ServiceResponse ws100013AuthServiceCheckByOtp(
        @WebParam(name = "request", targetNamespace = "")
        AuthServiceCheckRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100016_verifyLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100016_verifyLog", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100016VerifyLog")
    @ResponseWrapper(localName = "WS100016_verifyLogResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100016VerifyLogResponse")
    public ServiceResponse ws100016VerifyLog(
        @WebParam(name = "request", targetNamespace = "")
        VerifyLogRequestData request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100008_registerOTPRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100008_registerOTPRequest", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100008RegisterOTPRequest")
    @ResponseWrapper(localName = "WS100008_registerOTPRequestResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100008RegisterOTPRequestResponse")
    public ServiceResponse ws100008RegisterOTPRequest(
        @WebParam(name = "request", targetNamespace = "")
        RegisterOTPRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100015_authServiceCheckByCitizen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100015_authServiceCheckByCitizen", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100015AuthServiceCheckByCitizen")
    @ResponseWrapper(localName = "WS100015_authServiceCheckByCitizenResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100015AuthServiceCheckByCitizenResponse")
    public ServiceResponse ws100015AuthServiceCheckByCitizen(
        @WebParam(name = "request", targetNamespace = "")
        AuthServiceCheckByCitizenRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100012_authServiceByOtp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100012_authServiceByOtp", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100012AuthServiceByOtp")
    @ResponseWrapper(localName = "WS100012_authServiceByOtpResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100012AuthServiceByOtpResponse")
    public ServiceResponse ws100012AuthServiceByOtp(
        @WebParam(name = "request", targetNamespace = "")
        AuthServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100010_registerOTPByCitizen")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100010_registerOTPByCitizen", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100010RegisterOTPByCitizen")
    @ResponseWrapper(localName = "WS100010_registerOTPByCitizenResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100010RegisterOTPByCitizenResponse")
    public ServiceResponse ws100010RegisterOTPByCitizen(
        @WebParam(name = "request", targetNamespace = "")
        RegisterOtpByCitizenRequest request);

    /**
     * 
     * @return
     *     returns mn.gov.xyp.meta.ServiceResponse
     */
    @WebMethod(operationName = "WS100005_listOrganization")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WS100005_listOrganization", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100005ListOrganization")
    @ResponseWrapper(localName = "WS100005_listOrganizationResponse", targetNamespace = "http://meta.xyp.gov.mn/", className = "mn.gov.xyp.meta.WS100005ListOrganizationResponse")
    public ServiceResponse ws100005ListOrganization();

}
