
package mn.gov.xyp.meta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MetaServiceService", targetNamespace = "http://meta.xyp.gov.mn/", wsdlLocation = "https://xyp.gov.mn/meta-1.5.0/ws?WSDL")
public class MetaServiceService
    extends Service
{

    private final static URL METASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException METASERVICESERVICE_EXCEPTION;
    private final static QName METASERVICESERVICE_QNAME = new QName("http://meta.xyp.gov.mn/", "MetaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://xyp.gov.mn/meta-1.5.0/ws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        METASERVICESERVICE_WSDL_LOCATION = url;
        METASERVICESERVICE_EXCEPTION = e;
    }

    public MetaServiceService() {
        super(__getWsdlLocation(), METASERVICESERVICE_QNAME);
    }

    public MetaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), METASERVICESERVICE_QNAME, features);
    }

    public MetaServiceService(URL wsdlLocation) {
        super(wsdlLocation, METASERVICESERVICE_QNAME);
    }

    public MetaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, METASERVICESERVICE_QNAME, features);
    }

    public MetaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MetaService
     */
    @WebEndpoint(name = "MetaServicePort")
    public MetaService getMetaServicePort() {
        return super.getPort(new QName("http://meta.xyp.gov.mn/", "MetaServicePort"), MetaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MetaService
     */
    @WebEndpoint(name = "MetaServicePort")
    public MetaService getMetaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://meta.xyp.gov.mn/", "MetaServicePort"), MetaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (METASERVICESERVICE_EXCEPTION!= null) {
            throw METASERVICESERVICE_EXCEPTION;
        }
        return METASERVICESERVICE_WSDL_LOCATION;
    }

}
